on: [ push, pull_request ]
jobs:
  check_repository_cleanliness:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - id: "check_repository_cleanliness"
        run: |
          find . -name "#*#" -exec echo "::error file={},line=1,title=Unwanted file detected::{}" \;
          find . -name "*~" -exec echo "::error file={},line=1,title=Unwanted file detected::{}" \;
          find . -name "my_rpg" -exec echo "::error file={},line=1,title=Unwanted file detected::{}" \;
          find . -name "*.o" -exec echo "::error file={},line=1,title=Unwanted file detected::{}" \;
          find . -name "*.a" -exec echo "::error file={},line=1,title=Unwanted file detected::{}" \;
          find . -name "*.so" -exec echo "::error file={},line=1,title=Unwanted file detected::{}" \;
          find . -name "*.gcno" -exec echo "::error file={},line=1,title=Unwanted file detected::{}" \;
          find . -name "*.gcda" -exec echo "::error file={},line=1,title=Unwanted file detected::{}" \;
          find . -name "*.gcov" -exec echo "::error file={},line=1,title=Unwanted file detected::{}" \;
  check_compilation:
    runs-on: "ubuntu-latest"
    container: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v2
      - id: "check_array_make"
        run: cd lib/array_lib && make
      - id: "check_array_f_clean"
        run: cd lib/array_lib && make fclean
      - id: "check_convertor_make"
           run: cd lib/convertor && make
      - id: "check_convertor_f_clean"
          run: cd lib/convertor && make fclean
      - id: "check_print_make"
          run: cd lib/print_lib && make
      - id: "check_print_f_clean"
          run: cd lib/print_lib && make fclean
      - id: "check_str_make"
          run: cd lib/str_lib && make
      - id: "check_str_f_clean"
          run: cd lib/str_lib && make fclean

